export type Challenge = {
  nameID: string;
  displayName: string;
  tagline: string;
  background: string;
  vision: string;
  impact: string;
  who: string;
  country: string;
  city: string;
  refVideo: string;
  refJitsi: string;
  ref1Name: string;
  ref1Value: string;
  ref1Description: string;
  visualAvatar: string;
  visualBackground: string;
  visualBanner: string;
  leadingOrganizations: string[];
  memberOrganizations: string[];
  leadUsers: string[];
  tags: string[];
};
